# Generated by Django 4.0 on 2022-01-01 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Specialization', models.CharField(max_length=20)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('CNIC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Floors', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Security_Guard',
            fields=[
                ('CNIC', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Experience', models.IntegerField()),
                ('Hospital_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donation_system_app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Medicine', models.IntegerField()),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Staff', models.IntegerField()),
                ('Hospital_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donation_system_app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('CNIC', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Medical_Report', models.TextField()),
                ('Name', models.CharField(max_length=50)),
                ('Blood_Group', models.CharField(max_length=5)),
                ('Blood_Bank_Name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blood_donation_system_app.blood_bank')),
                ('Examined_By', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blood_donation_system_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Parking_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floors', models.IntegerField()),
                ('Space', models.IntegerField()),
                ('Time_Allotment', models.IntegerField()),
                ('Hospital_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donation_system_app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('CNIC', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Contact_Number', models.CharField(max_length=20)),
                ('Medical_Report', models.TextField()),
                ('Blood_Group', models.CharField(max_length=5)),
                ('Blood_Bank_Name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blood_donation_system_app.blood_bank')),
                ('Examined_By', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blood_donation_system_app.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Hospital_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donation_system_app.hospital'),
        ),
        migrations.AddField(
            model_name='blood_bank',
            name='Hospital_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donation_system_app.hospital'),
        ),
    ]
