# Generated by Django 4.0 on 2022-01-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation_system_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_bank',
            old_name='Hospital_Name',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Hospital_Name',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='parking_area',
            old_name='Hospital_Name',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='Hospital_Name',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='security_guard',
            old_name='Hospital_Name',
            new_name='Hospital',
        ),
    ]
