# Generated by Django 4.0 on 2022-01-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation_system_app', '0002_rename_hospital_name_blood_bank_hospital_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='Blood_Bank_Name',
            new_name='Blood_Bank',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Blood_Bank_Name',
            new_name='Blood_Bank',
        ),
    ]
