# Generated by Django 4.0 on 2022-01-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation_system_app', '0005_alter_donor_blood_bank_alter_donor_examined_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Blood_Bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blood_donation_system_app.blood_bank'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Examined_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blood_donation_system_app.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Blood_Bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blood_donation_system_app.blood_bank'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Examined_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blood_donation_system_app.doctor'),
        ),
    ]
